export const shoppingBatch = [
  {
    quantity: 2,
    packageSize: 12,
    itemName: 'Eggs',
    description: 'Large white eggs',
    measurement: 'each',
    category: 'dairy',
    notes: 'Buy if on sale',
    status: 'shopping-list',
    brandName: "Eggland's Best",
  },
  {
    quantity: 1,
    packageSize: 1,
    itemName: 'Milk',
    description: 'Whole milk',
    measurement: 'gallon',
    category: 'dairy',
    notes: '2% also okay',
    status: 'shopping-list',
    brandName: 'DairyPure',
  },
  {
    quantity: 2,
    packageSize: 1,
    itemName: 'Frozen Pizza',
    description: 'Pepperoni',
    measurement: 'each',
    category: 'frozen',
    notes: '',
    status: 'shopping-list',
    brandName: 'DiGiorno',
  },
  {
    quantity: 3,
    packageSize: 6,
    itemName: 'Bananas',
    description: 'Fresh bunch',
    measurement: 'each',
    category: 'produce',
    notes: 'Slightly green preferred',
    status: 'shopping-list',
    brandName: 'Dole',
  },
  {
    quantity: 1,
    packageSize: 16,
    itemName: 'Bread',
    description: 'Whole wheat loaf',
    measurement: 'slice',
    category: 'baked',
    notes: '',
    status: 'shopping-list',
    brandName: "Nature's Own",
  },
  {
    quantity: 1,
    packageSize: 1,
    itemName: 'Ground Beef',
    description: '85% lean',
    measurement: 'pound',
    category: 'meats-seafood',
    notes: 'Organic preferred',
    status: 'shopping-list',
    brandName: 'Market Pantry',
  },
  {
    quantity: 1,
    packageSize: 1,
    itemName: 'Yogurt',
    description: 'Strawberry',
    measurement: 'cup',
    category: 'dairy',
    notes: '',
    status: 'shopping-list',
    brandName: 'Chobani',
  },
  {
    quantity: 2,
    packageSize: 16,
    itemName: 'Cookies',
    description: 'Chocolate Chip',
    measurement: 'box',
    category: 'snacks',
    notes: 'Chewy',
    status: 'shopping-list',
    brandName: 'Chips Ahoy',
  },
  {
    quantity: 1,
    packageSize: 24,
    itemName: 'Cereal',
    description: 'Honey Oats',
    measurement: 'box',
    category: 'cereals',
    notes: 'Buy if on sale',
    status: 'shopping-list',
    brandName: 'Honey Bunches',
  },
  {
    quantity: 2,
    packageSize: 1,
    itemName: 'Chicken Breast',
    description: 'Boneless skinless',
    measurement: 'pound',
    category: 'meats-seafood',
    notes: '',
    status: 'shopping-list',
    brandName: 'Tyson',
  },
  {
    quantity: 1,
    packageSize: 1,
    itemName: 'Orange Juice',
    description: 'No pulp',
    measurement: 'quart',
    category: 'beverages',
    notes: '100% juice only',
    status: 'shopping-cart',
    brandName: 'Tropicana',
  },
  {
    quantity: 2,
    packageSize: 6,
    itemName: 'Apples',
    description: 'Fuji',
    measurement: 'each',
    category: 'produce',
    notes: 'Firm & red',
    status: 'shopping-cart',
    brandName: 'Dole',
  },
  {
    quantity: 1,
    packageSize: 1,
    itemName: 'Ketchup',
    description: 'Tomato',
    measurement: 'bottle',
    category: 'condiments',
    notes: '',
    status: 'shopping-cart',
    brandName: 'Heinz',
  },
  {
    quantity: 1,
    packageSize: 1,
    itemName: 'Shredded Cheese',
    description: 'Cheddar blend',
    measurement: 'cup',
    category: 'dairy',
    notes: '',
    status: 'shopping-cart',
    brandName: 'Sargento',
  },
  {
    quantity: 1,
    packageSize: 1,
    itemName: 'Spaghetti',
    description: 'Thin pasta',
    measurement: 'box',
    category: 'dry-pasta',
    notes: '',
    status: 'shopping-cart',
    brandName: 'Barilla',
  },
  {
    quantity: 1,
    packageSize: 12,
    itemName: 'Soda',
    description: 'Cola',
    measurement: 'fluidounce',
    category: 'beverages',
    notes: '',
    status: 'shopping-cart',
    brandName: 'Coca-Cola',
  },
  {
    quantity: 1,
    packageSize: 15,
    itemName: 'Canned Beans',
    description: 'Black beans',
    measurement: 'ounce',
    category: 'canned',
    notes: '',
    status: 'shopping-cart',
    brandName: 'Bush’s',
  },
  {
    quantity: 2,
    packageSize: 1,
    itemName: 'Ice Cream',
    description: 'Vanilla',
    measurement: 'pint',
    category: 'frozen',
    notes: 'Any brand',
    status: 'shopping-cart',
    brandName: 'Ben & Jerry’s',
  },
  {
    quantity: 1,
    packageSize: 1,
    itemName: 'Flour',
    description: 'All-purpose',
    measurement: 'pound',
    category: 'baking',
    notes: '',
    status: 'shopping-cart',
    brandName: 'Gold Medal',
  },
  {
    quantity: 1,
    packageSize: 1,
    itemName: 'Olive Oil',
    description: 'Extra virgin',
    measurement: 'liter',
    category: 'spices',
    notes: '',
    status: 'shopping-cart',
    brandName: 'Bertolli',
  },
];

export const cupboardBatch = [
  {
    itemName: 'Eggs',
    brandName: 'Farm Fresh',
    description: 'Large brown eggs',
    packageSize: 12,
    remainingAmount: 8,
    measurement: 'ct',
    category: 'Dairy',
    notes: 'Use for breakfast and baking',
    quantity: 1,
  },
  {
    itemName: 'Milk',
    brandName: 'Dairy Pure',
    description: '2% reduced fat milk',
    packageSize: 1,
    remainingAmount: 0.4,
    measurement: 'gal',
    category: 'Dairy',
    notes: '',
    quantity: 1,
  },
  {
    itemName: 'Rice',
    brandName: 'Uncle Ben’s',
    description: 'Long grain white rice',
    packageSize: 5,
    remainingAmount: 2,
    measurement: 'lb',
    category: 'Pantry',
    notes: 'Running low',
    quantity: 1,
  },
  {
    itemName: 'Black Beans',
    brandName: 'Goya',
    description: 'Canned black beans',
    packageSize: 15.5,
    remainingAmount: 15.5,
    measurement: 'oz',
    category: 'Canned Goods',
    notes: '',
    quantity: 1,
  },
  {
    itemName: 'Olive Oil',
    brandName: 'Bertolli',
    description: 'Extra virgin olive oil',
    packageSize: 750,
    remainingAmount: 500,
    measurement: 'ml',
    category: 'Pantry',
    notes: '',
    quantity: 1,
  },
  {
    itemName: 'Bread',
    brandName: 'Sara Lee',
    description: 'Whole grain sandwich bread',
    packageSize: 18,
    remainingAmount: 6,
    measurement: 'slices',
    category: 'Bakery',
    notes: 'Getting stale',
    quantity: 1,
  },
  {
    itemName: 'Butter',
    brandName: 'Land O Lakes',
    description: 'Salted stick butter',
    packageSize: 4,
    remainingAmount: 1,
    measurement: 'sticks',
    category: 'Dairy',
    notes: '',
    quantity: 1,
  },
  {
    itemName: 'Carrots',
    brandName: 'Organic Valley',
    description: 'Baby carrots',
    packageSize: 2,
    remainingAmount: 0.5,
    measurement: 'lb',
    category: 'Produce',
    notes: '',
    quantity: 1,
  },
  {
    itemName: 'Chicken Breast',
    brandName: 'Tyson',
    description: 'Boneless skinless',
    packageSize: 2.5,
    remainingAmount: 1.2,
    measurement: 'lb',
    category: 'Meat',
    notes: 'Frozen',
    quantity: 1,
  },
  {
    itemName: 'Pasta',
    brandName: 'Barilla',
    description: 'Spaghetti noodles',
    packageSize: 16,
    remainingAmount: 10,
    measurement: 'oz',
    category: 'Pantry',
    notes: 'Dry goods',
    quantity: 1,
  },
];
